version: '2'
services:
  web:
    image: python
    command: python -m http.server 8080 --directory /www/data
    volumes:
      - ./index.html:/www/data/index.html
    ports:
      - "8080:8080"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
