version: '2'
services:
  web:
    build: app
    command: npm run dev
    volumes:
      - ./app:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
